#   _____         _     __ _ _
# |_   _|_ _ ___| | __/ _(_) | ___
#   | |/ _` / __| |/ / |_| | |/ _ \
#   | | (_| \__ \   <|  _| | |  __/
#   |_|\__,_|___/_|\_\_| |_|_|\___|
#
# https://taskfile.dev
#

version: '3'

silent: true

##
## ===   Variables ==================================================
##

vars:
  #
  # DOCKER
  DOCKER: docker
  DOCKER_FILE: docker-compose.yml
  DOCKER_RUN: "{{.DOCKER}} run"
  DOCKER_COMPOSE: "{{.DOCKER}} compose"

##
## ===   TASKS ==================================================
##

tasks:
  default:
    cmds:
      - task: help

  help:
    desc: "Description des tâches disponibles"
    cmds:
      - echo " ";
      - echo "Welcome to Cyber Audit Code PHP"
      - echo " ";
      - echo " 📦 YOUR SYSTEM ---------------------------------------------------------"
      - echo 'Your system "{{OS}}" / "{{ARCH}}"'
      - echo " ";
      - echo " 📦 ESSENTIAL TASK ---------------------------------------------------------"
      - echo "* start               Start project"
      - echo "* stop                Stop project"
      - echo " ";
      - echo " 🎛️ OTHER TASK ----------------------------------------------------------"
      - task --list


  ## === 🐋  DOCKER ================================================

  docker-up:
    desc: "Start docker containers"
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d"

  docker-stop:
    desc: "Stop docker containers"
    cmds:
      - "{{.DOCKER_COMPOSE}} stop"

  docker-down:
    desc: "Stop and remove docker containers, networks.."
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  docker-reset:
    desc: "Stop and reset on your environment"
    cmds:
      - "{{.DOCKER_COMPOSE}} down -v"

  ## === 🐋  SCRIPT ================================================

  start:
    desc: "Start"
    cmds:
      - |
        task docker-up 

  stop:
    desc: "Stop"
    cmds:
      - |
        echo "Are you docker stop or down ? [S/d] :"
        read CONFIRM_DOCKER
        if [ "$CONFIRM_DOCKER" = "d" ]; then
          task docker-down
        else
          task docker-stop
        fi

  reset:
    desc: "Reset"
    cmds:
      - |
        echo "Are you sure you want to reset ? [y/N] :"
        read CONFIRM
        if [ "$CONFIRM" = "y" ]; then
          task docker-reset
          rm -r var
        fi
